### ISSUE TITLE
Basic things for a starter kit

### ISSUE THREAD

**Issue by rNoz** [Abuntxa/quasar-demo-typescript#1]
Hi.

I know this is your repo, your code and your own tests.

I have been trying just yesterday the same as you, but with the default config, including prettier support. I really don't like the src="./hello.ts" approach (apart from being optional), and I would like to use typescript+vue in the same file. Maybe you know more about it.

I tried to just use a simple component like src/components/Hello.vue

```
<template>
    <q-page class="flex flex-center">
        <p class="greeting">Hello {{name}}{{exclamationMarks}}</p>
        <q-btn @click="decrement">-</q-btn>
        <q-btn @click="increment">+</q-btn>
    </q-page>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
@Component
export default class HelloDecorator extends Vue {
    @Prop() name!: string;
    @Prop({default: 1}) initialEnthusiasm!: number;
    enthusiasm = this.initialEnthusiasm;
    increment() {
        this.enthusiasm++;
    }
    decrement() {
        if (this.enthusiasm > 1) {
            this.enthusiasm--;
        }
    }
    get exclamationMarks(): string {
        return Array(this.enthusiasm + 1).join('!');
    }
}
</script>

<style>
.greeting {
    font-size: 20px;
}
</style>
```

With no luck. It is extracted from this [gist](https://gist.github.com/snowyu/67f417c3f40f3471608aa78b6e182e39).

Seeing that you are trying almost the same, would be great if you can achieve to use something like this in a typical new project (quasar-cli create, with axios, i18n, prettier, etc).

Some other refs and projects doing the same [1](https://github.com/quasarframework/app-extension-typescript) or [2](https://github.com/paoloar77/FreePlanet).

**Comment by Abuntxa** [comment]
Hi,
I created the repo in order to ask for some help in the quasar/#typescript
discord channel.
They answered me that they would look into it on Monday.
I'm a newby into webpack so it will take me some time to get it on my
own...
From my point of view the typescript extension should handle this on its
own. I find this issue important too, so I won't let it go.
I'll keep you posted with the news.
Best regards
Jon

**Comment by Abuntxa** [comment]
Hau idatzi du Jon Abaunza (jon.abaunza@gmail.com) erabiltzaileak (2019 mar.
31, ig. (19:45)):

> Hi,
> I created the repo in order to ask for some help in the quasar/#typescript
> discord channel.
> They answered me that they would look into it on Monday.
> I'm a newby into webpack so it will take me some time to get it on my
> own...
> From my point of view the typescript extension should handle this on its
> own. I find this issue important too, so I won't let it go.
> I'll keep you posted with the news.
> Best regards
> Jon
>

**Comment by Abuntxa** [comment]
Hi,

I just found the problem that did not allow me to have the vue single file
components with typescript working. The quasar app bootstrap project
includes an extra build section for linting the ES6. The typescript
extension already introduces the typescript loading with its own typescript
linting.
Removing the extra build configuration solved my issues.

I have updated the repository

Best regards

Hau idatzi du Jon Abaunza (jon.abaunza@gmail.com) erabiltzaileak (2019 mar.
31, ig. (19:45)):

> Hi,
> I created the repo in order to ask for some help in the quasar/#typescript
> discord channel.
> They answered me that they would look into it on Monday.
> I'm a newby into webpack so it will take me some time to get it on my
> own...
> From my point of view the typescript extension should handle this on its
> own. I find this issue important too, so I won't let it go.
> I'll keep you posted with the news.
> Best regards
> Jon
>

**Comment by rNoz** [comment]
Thanks, I will try.

That is something "weird" because it is suppose that the official repos are using also that step. Also, it will make sense to be able to combine .js and .ts in a project, and when using Vue script with a type="ts" it should omit that section. But still, it is something ;)

I suppose it needs a bit more maturity. It should work by default with the best combination: typescript, eslint, prettier, etc.
